### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by CarolePepper** [zhuchunshu/super-forum#27]
![屏幕截图 2022-05-22 102257](https://user-images.githubusercontent.com/97326465/169675623-21774e03-0b23-4d54-968c-82482bab241b.png)
![屏幕截图 2022-05-22 102434](https://user-images.githubusercontent.com/97326465/169675631-23ebd5ac-07f1-4e9d-807b-44bbfe5e096a.png)

![屏幕截图 2022-05-22 102710](https://user-images.githubusercontent.com/97326465/169675681-c25ec416-b173-4957-9a3e-c4fa790b576f.png)

![屏幕截图 2022-05-22 103131](https://user-images.githubusercontent.com/97326465/169675739-e4aa88ab-8ef7-4044-935a-c7240dd341ca.png)

1. 建议把当前使用的‘标签’改为分类 或者圈子 可以参考 [Learnku](https://learnku.com/go)
2. 用户发帖可以给帖子自定义添加标签 在列表页和板块一起显示 例如上图
3. 分类列表右侧是否可以加入当前分类的介绍和用户可以加入这个分类的功能呢 ？还有就是分类板块版主管理员申请

**Comment by CarolePepper** [comment]
![屏幕截图 2022-05-22 104618](https://user-images.githubusercontent.com/97326465/169676025-232e492b-527b-44f0-b613-2174ccdcb3fd.png)

![屏幕截图 2022-05-22 104517](https://user-images.githubusercontent.com/97326465/169676027-fd8b0653-6b4f-472f-b36f-489702a583c3.png)
![屏幕截图 2022-05-22 104531](https://user-images.githubusercontent.com/97326465/169676028-a17ea682-351e-44ac-9b2a-f516a4cab8eb.png)

最新   最赞  热门 这些 建议使用上图中这种下拉菜单方式

**Comment by zhuchunshu** [comment]
好的，非常感谢大佬建议
