### ISSUE TITLE
未登录点击发帖按钮有问题

### ISSUE THREAD

**Issue by CarolePepper** [zhuchunshu/super-forum#28]
![屏幕截图 2022-05-22 123919](https://user-images.githubusercontent.com/97326465/169678950-2dce4fa8-5e3b-4ce4-9062-632bbb8f0d3a.png)

当前是直接跳转提示403 这样用户体验不是很好  而没有正确的跳转到登录页面

**Comment by zhuchunshu** [comment]
感谢反馈
