### ISSUE TITLE
是否可以加入用户上传用户中心背景图片功能？

### ISSUE THREAD

**Issue by CarolePepper** [zhuchunshu/super-forum#29]
![屏幕截图 2022-05-22 105045](https://user-images.githubusercontent.com/97326465/169678981-2cd60d71-21d3-4acc-bcdb-851a96374ac2.png)

**Comment by zhuchunshu** [comment]
感谢建议,安排

**Comment by zhuchunshu** [comment]
[https://github.com/zhuchunshu/super-forum/commit/7383abe830148aa9c1a32b766b08ca1accee1484](https://github.com/zhuchunshu/super-forum/commit/7383abe830148aa9c1a32b766b08ca1accee1484)
