### ISSUE TITLE
建议导航栏合并为一个而非两个导航栏

### ISSUE THREAD

**Issue by CarolePepper** [zhuchunshu/super-forum#30]
![屏幕截图 2022-05-22 124233](https://user-images.githubusercontent.com/97326465/169679059-5057cc51-3bae-486a-86ae-6465ed8c7de4.png)

**Comment by zhuchunshu** [comment]
好的，不过这个可以通过切换主题实现,例如这个主题:[https://www.runpod.cn/124.html](https://www.runpod.cn/124.html)

**Comment by CarolePepper** [comment]
> 好的，不过这个可以通过切换主题实现,例如这个主题:https://www.runpod.cn/124.html

这个主题主题还是双导航栏呢     不过模板文件是PHP文件会不是自定义主题会很麻烦呢？对了有QQ交流群吗 或者邮箱地址呢

**Comment by zhuchunshu** [comment]
> > 好的，不过这个可以通过切换主题实现,例如这个主题:https://www.runpod.cn/124.html
> 
> 这个主题主题还是双导航栏呢 不过模板文件是PHP文件会不是自定义主题会很麻烦呢？对了有QQ交流群吗 或者邮箱地址呢

感谢支持,QQ交流群: 798695907
