### ISSUE TITLE
官网出错了

### ISSUE THREAD

**Issue by yanwen** [zhuchunshu/super-forum#38]
https://www.runpod.cn/

`Warning: include(/www/wwwroot/super-forum/runtime/view//be68b7110f7bbb9a39dc375e13ccb699031acfce.php): Failed to open stream: No such file or directory in /www/wwwroot/super-forum/vendor/hyperf/view-engine/src/Engine/PhpEngine.php on line 64 Warning: include(): Failed opening '/www/wwwroot/super-forum/runtime/view//be68b7110f7bbb9a39dc375e13ccb699031acfce.php' for inclusion (include_path='.:') in /www/wwwroot/super-forum/vendor/hyperf/view-engine/src/Engine/PhpEngine.php on line 64`

可以修复一下不？

**Comment by zhuchunshu** [comment]
感谢反馈，已修复
主要是今天在更新，刚好我在讲课，弄了一半
