### ISSUE TITLE
建议附一个简易的部署教程

### ISSUE THREAD

**Issue by KormiMeiko** [zhuchunshu/super-forum#4]
如题~

**Comment by zhuchunshu** [comment]
开发阶段
预计十一月下旬发布正式版以及部署教程

**Comment by KormiMeiko** [comment]
> 开发阶段 预计十一月下旬发布正式版以及部署教程

目前这个版本部署的话，可以顺利升级到正式版嘛

**Comment by zhuchunshu** [comment]
> > 开发阶段 下一个十一月下旬正式发布版本以及开发教程
> 
> 现在版本部署的话，可以顺利升级到正式版嘛

可以，但不建议
